### ISSUE TITLE
Problems with package LieberInstitute/jaffelab

### ISSUE THREAD

**Issue by ehatl** [LieberInstitute/SPEAQeasy#72]
I try to install the SPEAQeasy in my local computer but when I run "install_software.sh" it crash in some part.
Do you have some idea for fix it?

The error message is it:

Loading required package: rafalib
Error: package or namespace load failed for ‘jaffelab’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘segmented’
Execution halted

Great and thanks in advance

**Comment by lcolladotor** [comment]
Hi,

Could you provide us more information on how and where you ran `install_software.sh`? Like, are you using Docker?

In any case, you could try opening R manually and installing `segmented` with `install.packages("segmented")`. Then, `remotes::install_github("LieberInstitute/jaffelab")` should proceed.

Best,
Leo

**Comment by ehatl** [comment]
Thanks for answered.
I can resolved the problem with the recommendation that you send me.
I have some problems with the ca-certificates but I can resolved with this command `sudo update-ca-certificates`. Others packages in R that I need to installed was "remote" and "getopt" or "optget" (I dont remeber it name), then I can did the recommendation than you send me and now is installed. Now I test it.
I installed it in a Linux/Ubuntu 18.04.5 LTS, I didn't use Docker
Thanks a lot
Best
Ulises

**Comment by Nick-Eagles** [comment]
Hello,

I'm glad that solution worked for you. I was able to reproduce the issue you had with the `jaffelab` installation, and just now addressed it with [this commit](https://github.com/LieberInstitute/SPEAQeasy/commit/19ee0ff), so a manual fix shouldn't be necessary for others in the future. Thanks for reaching out.

Best,
-Nick

**Comment by mbartl13** [comment]
Hi Nick,

I am getting the same error with bash install_software.sh "jhpce" on the Hopkins cluster. 

I tried the approach listed above but no luck, then I tried replacing the check_R_packages.R with the script in the commit referenced above but still getting the same:

[mbartlet@compute-105 SPEAQeasy]$ bash install_software.sh "jhpce"
User selected set-up at JHPCE. Installing any missing R packages...
Loading conda_R/4.0.x
Bioconductor version '3.12' is out-of-date; the current release version '3.13'
  is available with R version '4.1'; see https://bioconductor.org/install



[1] "All ordinary packages are already installed."
[1] "Done checking/installing packages."
Loading required package: usethis
─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.0.4 RC (2021-02-08 r79975)
 os       CentOS Linux 7 (Core)
 system   x86_64, linux-gnu
 ui       X11
 language en_US.UTF-8
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       US/Eastern
 date     2021-07-12

─ Packages ───────────────────────────────────────────────────────────────────
 package                      * version  date       lib source
 AnnotationDbi                  1.52.0   2020-10-27 [2] Bioconductor
 askpass                        1.1      2019-01-13 [2] CRAN (R 4.0.3)
 assertthat                     0.2.1    2019-03-21 [2] CRAN (R 4.0.3)
 backports                      1.2.1    2020-12-09 [2] CRAN (R 4.0.3)
 base64enc                      0.1-3    2015-07-28 [2] CRAN (R 4.0.3)
 Biobase                        2.50.0   2020-10-27 [2] Bioconductor
 BiocFileCache                  1.14.0   2020-10-27 [2] Bioconductor
 BiocGenerics                   0.36.1   2021-04-16 [2] Bioconductor
 BiocManager                    1.30.12  2021-03-28 [2] CRAN (R 4.0.4)
 BiocParallel                   1.24.1   2020-11-06 [2] Bioconductor
 biomaRt                        2.46.3   2021-02-09 [2] Bioconductor
 Biostrings                     2.58.0   2020-10-27 [2] Bioconductor
 bit                            4.0.4    2020-08-04 [2] CRAN (R 4.0.3)
 bit64                          4.0.5    2020-08-30 [2] CRAN (R 4.0.3)
 bitops                         1.0-7    2021-04-24 [2] CRAN (R 4.0.4)
 blob                           1.2.1    2020-01-20 [2] CRAN (R 4.0.3)
 BSgenome                       1.58.0   2020-10-27 [2] Bioconductor
 BSgenome.Hsapiens.UCSC.hg19    1.4.3    2021-07-12 [1] Bioconductor
 BSgenome.Hsapiens.UCSC.hg38    1.4.3    2021-04-14 [2] Bioconductor
 BSgenome.Mmusculus.UCSC.mm10   1.4.0    2021-07-12 [1] Bioconductor
 bumphunter                     1.32.0   2020-10-27 [2] Bioconductor
 cachem                         1.0.4    2021-02-13 [2] CRAN (R 4.0.4)
 callr                          3.7.0    2021-04-20 [2] CRAN (R 4.0.4)
 checkmate                      2.0.0    2020-02-06 [2] CRAN (R 4.0.3)
 cli                            2.5.0    2021-04-26 [2] CRAN (R 4.0.4)
 cluster                        2.1.2    2021-04-17 [3] CRAN (R 4.0.4)
 codetools                      0.2-18   2020-11-04 [3] CRAN (R 4.0.4)
 colorspace                     2.0-0    2020-11-11 [2] CRAN (R 4.0.3)
 crayon                         1.4.1    2021-02-08 [2] CRAN (R 4.0.3)
 curl                           4.3      2019-12-02 [2] CRAN (R 4.0.3)
 data.table                     1.14.0   2021-02-21 [2] CRAN (R 4.0.4)
 DBI                            1.1.1    2021-01-15 [2] CRAN (R 4.0.3)
 dbplyr                         2.1.1    2021-04-06 [2] CRAN (R 4.0.4)
 DelayedArray                   0.16.3   2021-03-24 [2] Bioconductor
 derfinder                      1.24.2   2020-12-18 [2] Bioconductor
 derfinderHelper                1.24.1   2020-12-18 [2] Bioconductor
 desc                           1.3.0    2021-03-05 [2] CRAN (R 4.0.4)
 devtools                     * 2.4.0    2021-04-07 [2] CRAN (R 4.0.4)
 digest                         0.6.27   2020-10-24 [2] CRAN (R 4.0.3)
 doRNG                          1.8.2    2020-01-27 [2] CRAN (R 4.0.3)
 dplyr                          1.0.5    2021-03-05 [2] CRAN (R 4.0.4)
 ellipsis                       0.3.2    2021-04-29 [2] CRAN (R 4.0.4)
 fansi                          0.4.2    2021-01-15 [2] CRAN (R 4.0.3)
 fastmap                        1.1.0    2021-01-25 [2] CRAN (R 4.0.3)
 foreach                        1.5.1    2020-10-15 [2] CRAN (R 4.0.3)
 foreign                        0.8-81   2020-12-22 [3] CRAN (R 4.0.4)
 Formula                        1.2-4    2020-10-16 [2] CRAN (R 4.0.3)
 fs                             1.5.0    2020-07-31 [2] CRAN (R 4.0.3)
 generics                       0.1.0    2020-10-31 [2] CRAN (R 4.0.3)
 GenomeInfoDb                   1.26.7   2021-04-08 [2] Bioconductor
 GenomeInfoDbData               1.2.4    2020-11-30 [2] Bioconductor
 GenomicAlignments              1.26.0   2020-10-27 [2] Bioconductor
 GenomicFeatures                1.42.3   2021-04-01 [2] Bioconductor
 GenomicFiles                   1.26.0   2020-10-27 [2] Bioconductor
 GenomicRanges                  1.42.0   2020-10-27 [2] Bioconductor
 getopt                         1.20.3   2019-03-22 [2] CRAN (R 4.0.3)
 ggplot2                        3.3.3    2020-12-30 [2] CRAN (R 4.0.3)
 glue                           1.4.2    2020-08-27 [2] CRAN (R 4.0.3)
 gridExtra                      2.3      2017-09-09 [2] CRAN (R 4.0.3)
 gtable                         0.3.0    2019-03-25 [2] CRAN (R 4.0.3)
 Hmisc                          4.5-0    2021-02-28 [2] CRAN (R 4.0.4)
 hms                            1.0.0    2021-01-13 [2] CRAN (R 4.0.3)
 htmlTable                      2.1.0    2020-09-16 [2] CRAN (R 4.0.3)
 htmltools                      0.5.1.1  2021-01-22 [2] CRAN (R 4.0.3)
 htmlwidgets                    1.5.3    2020-12-10 [2] CRAN (R 4.0.3)
 httr                           1.4.2    2020-07-20 [2] CRAN (R 4.0.3)
 IRanges                        2.24.1   2020-12-12 [2] Bioconductor
 iterators                      1.0.13   2020-10-15 [2] CRAN (R 4.0.3)
 jpeg                           0.1-8.1  2019-10-24 [2] CRAN (R 4.0.3)
 knitr                          1.33     2021-04-24 [2] CRAN (R 4.0.4)
 lattice                        0.20-41  2020-04-02 [3] CRAN (R 4.0.4)
 latticeExtra                   0.6-29   2019-12-19 [2] CRAN (R 4.0.3)
 lifecycle                      1.0.0    2021-02-15 [2] CRAN (R 4.0.4)
 locfit                         1.5-9.4  2020-03-25 [2] CRAN (R 4.0.3)
 magrittr                       2.0.1    2020-11-17 [2] CRAN (R 4.0.3)
 Matrix                         1.3-2    2021-01-06 [3] CRAN (R 4.0.4)
 MatrixGenerics                 1.2.1    2021-01-30 [2] Bioconductor
 matrixStats                    0.58.0   2021-01-29 [2] CRAN (R 4.0.3)
 memoise                        2.0.0    2021-01-26 [2] CRAN (R 4.0.3)
 munsell                        0.5.0    2018-06-12 [2] CRAN (R 4.0.3)
 nnet                           7.3-15   2021-01-24 [3] CRAN (R 4.0.4)
 openssl                        1.4.3    2020-09-18 [2] CRAN (R 4.0.3)
 org.Hs.eg.db                   3.12.0   2020-12-01 [2] Bioconductor
 org.Mm.eg.db                   3.12.0   2021-07-12 [1] Bioconductor
 org.Rn.eg.db                   3.12.0   2020-10-30 [1] Bioconductor
 pillar                         1.6.0    2021-04-13 [2] CRAN (R 4.0.4)
 pkgbuild                       1.2.0    2020-12-15 [2] CRAN (R 4.0.3)
 pkgconfig                      2.0.3    2019-09-22 [2] CRAN (R 4.0.3)
 pkgload                        1.2.1    2021-04-06 [2] CRAN (R 4.0.4)
 plyr                           1.8.6    2020-03-03 [2] CRAN (R 4.0.3)
 png                            0.1-7    2013-12-03 [2] CRAN (R 4.0.3)
 prettyunits                    1.1.1    2020-01-24 [2] CRAN (R 4.0.3)
 processx                       3.5.1    2021-04-04 [2] CRAN (R 4.0.4)
 progress                       1.2.2    2019-05-16 [2] CRAN (R 4.0.3)
 ps                             1.6.0    2021-02-28 [2] CRAN (R 4.0.4)
 purrr                          0.3.4    2020-04-17 [2] CRAN (R 4.0.3)
 qvalue                         2.22.0   2020-10-27 [2] Bioconductor
 R6                             2.5.0    2020-10-28 [2] CRAN (R 4.0.3)
 rafalib                        1.0.0    2015-08-09 [1] CRAN (R 4.0.3)
 rappdirs                       0.3.3    2021-01-31 [2] CRAN (R 4.0.3)
 RColorBrewer                   1.1-2    2014-12-07 [2] CRAN (R 4.0.3)
 Rcpp                           1.0.6    2021-01-15 [2] CRAN (R 4.0.3)
 RCurl                          1.98-1.3 2021-03-16 [2] CRAN (R 4.0.4)
 remotes                        2.3.0    2021-04-01 [2] CRAN (R 4.0.4)
 reshape2                       1.4.4    2020-04-09 [2] CRAN (R 4.0.3)
 rlang                          0.4.10   2020-12-30 [2] CRAN (R 4.0.3)
 rngtools                       1.5      2020-01-23 [2] CRAN (R 4.0.3)
 rpart                          4.1-15   2019-04-12 [3] CRAN (R 4.0.4)
 rprojroot                      2.0.2    2020-11-15 [2] CRAN (R 4.0.3)
 Rsamtools                      2.6.0    2020-10-27 [2] Bioconductor
 RSQLite                        2.2.7    2021-04-22 [2] CRAN (R 4.0.4)
 rstudioapi                     0.13     2020-11-12 [2] CRAN (R 4.0.3)
 rtracklayer                    1.50.0   2020-10-27 [2] Bioconductor
 S4Vectors                      0.28.1   2020-12-09 [2] Bioconductor
 scales                         1.1.1    2020-05-11 [2] CRAN (R 4.0.3)
 sessioninfo                    1.1.1    2018-11-05 [2] CRAN (R 4.0.3)
 stringi                        1.5.3    2020-09-09 [2] CRAN (R 4.0.3)
 stringr                        1.4.0    2019-02-10 [2] CRAN (R 4.0.3)
 SummarizedExperiment           1.20.0   2020-10-27 [2] Bioconductor
 survival                       3.2-9    2021-03-14 [3] CRAN (R 4.0.4)
 testthat                       3.0.2    2021-02-14 [2] CRAN (R 4.0.4)
 tibble                         3.1.1    2021-04-18 [2] CRAN (R 4.0.4)
 tidyselect                     1.1.1    2021-04-30 [2] CRAN (R 4.0.4)
 usethis                      * 2.0.1    2021-02-10 [2] CRAN (R 4.0.4)
 utf8                           1.2.1    2021-03-12 [2] CRAN (R 4.0.4)
 VariantAnnotation              1.36.0   2020-10-27 [2] Bioconductor
 vctrs                          0.3.8    2021-04-29 [2] CRAN (R 4.0.4)
 withr                          2.4.2    2021-04-18 [2] CRAN (R 4.0.4)
 xfun                           0.22     2021-03-11 [2] CRAN (R 4.0.4)
 XML                            3.99-0.6 2021-03-16 [2] CRAN (R 4.0.4)
 xml2                           1.3.2    2020-04-23 [2] CRAN (R 4.0.3)
 XVector                        0.30.0   2020-10-27 [2] Bioconductor
 zlibbioc                       1.36.0   2020-10-27 [2] Bioconductor

[1] /users/mbartlet/R/4.0.x
[2] /jhpce/shared/jhpce/core/conda/miniconda3-4.6.14/envs/svnR-4.0.x/R/4.0.x/lib64/R/site-library
[3] /jhpce/shared/jhpce/core/conda/miniconda3-4.6.14/envs/svnR-4.0.x/R/4.0.x/lib64/R/library
Setting up test files...
Loading required package: rafalib
Error: package or namespace load failed for ‘jaffelab’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘segmented’
Execution halted

Thanks in advance!
Maggie

**Comment by Nick-Eagles** [comment]
Hi Maggie,

It looks like for some reason `check_R_packages_JHPCE.R` isn't detecting that `jaffelab` isn't installed. Can you try this from within the SPEAQeasy repo:

```
module load conda_R/4.0.x
Rscript -e "remotes::install_github('LieberInstitute/jaffelab')"
bash install_software.sh "jhpce"
```

Basically, I'm hoping the issue will be resolved if you manually install `jaffelab`. If that's the case, I'll have to update `check_R_packages_JHPCE.R`, since you shouldn't have to manually install any packages for the SPEAQeasy installation to work.

Best,
-Nick

**Comment by mbartl13** [comment]
Thanks for the insight Nick, that worked!

Thanks again,
Maggie
________________________________
